CXX = g++
CXXFLAGS = -std=c++20 -Ilib -I/opt/homebrew/include
LDFLAGS = -L/opt/homebrew/lib -Wl,-rpath,/usr/local/lib 
LIBS = -lboost_system -lboost_thread -lssl -lcrypto -pthread -lredis++
SOURCES = main.cpp logger.cpp binance_spot_handler.cpp websocket_client.cpp 
EXECUTABLE = main

$(EXECUTABLE): $(SOURCES)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -f $(EXECUTABLE)